#ifndef CFUSA_VERSION_H
#define CFUSA_VERSION_H

#define CFUSA_VERSION_MAJOR  0
#define CFUSA_VERSION_MINOR  2
#define CFUSA_VERSION_PATCH  0
#define CFUSA_VERSION_STRING "0.2.0"

#endif /* CFUSA_VERSION_H */
