#ifndef CFUSA_VERSION_H
#define CFUSA_VERSION_H

#define CFUSA_VERSION_MAJOR  0
#define CFUSA_VERSION_MINOR  5
#define CFUSA_VERSION_PATCH  41
#define CFUSA_VERSION_STRING "0.5.41"
#define CFUSA_SCHEMA_VERSION "1.10.12"
#define CFUSA_SPEC_VERSION   "1.10.12"

#endif /* CFUSA_VERSION_H */
